evitement_obstacle_node:
  ros__parameters:
    distance_arret_mm: 350
    vitesse_avance: 500
    periode_publication_s: 0.1
    distance_invalide_arrete: true
    angle_tourelle_centre_deg: 95
    angle_tourelle_gauche_deg: 140
    angle_tourelle_droite_deg: 45
    delai_stabilisation_tourelle_s: 0.35
    distance_degagement_mm: 600
    mesures_degagement_requises: 3
    vitesse_rotation_recherche: 300
    vitesse_recul: 300
    duree_rotation_recherche_max_s: 4.0
    duree_recul_s: 0.45
    marge_choix_direction_mm: 120
